const express = require("express");
const router = express.Router();
const Analytics = require("../Models/analyticsModel");
const stringSimilarity = require("string-similarity");
const Synonym = require("../Models/synonymModel");

router.post("/analytics", async (req, res) => {

  try {

    const {
      vendor,
      type,
      query,
      productId,
      resultsCount: incomingResultsCount,
      productHandle,
      store,
      productTitle,
      productImage
    } = req.body;

    const allowedTypes = [
      "search",
      "click",
      "no_result"
    ];

    if (
      !allowedTypes.includes(type)
    ) {

      return res.status(400).json({
        error:
          "Invalid analytics type"
      });

    }

    if (
      process.env.NODE_ENV !==
      "production"
    ) {

      console.log(
        "BODY RECEIVED:",
        req.body
      );

    }

    if (!store) {

      return res.status(400).json({
        error:
          "Store is required"
      });

    }

    if (
      type === "search" &&
      !query?.trim()
    ) {

      return res.json({
        success: false
      });

    }

    const normalizedStore =
      store
        ?.trim()
        ?.toLowerCase();

    const normalizedQuery =
      query
        ?.trim()
        ?.toLowerCase();

    const userAgent =
      req.headers[
      "user-agent"
      ] || "";

    const resultsCount =
      type === "no_result"
        ? 0
        : Number(
          incomingResultsCount
        ) || 0;

    // =====================================
    // 🔥 SAVE ANALYTICS
    // =====================================

    await Analytics.create({

      type,

      query:
        query?.trim() || "",

      normalizedQuery,

      productId,

      productTitle:
        productTitle || null,

      productHandle:
        productHandle || null,

      productImage:
        productImage || null,

      vendor:
        vendor
          ?.trim()
          ?.toLowerCase() || null,

      store:
        normalizedStore,

      device:
        userAgent.includes(
          "Mobile"
        )
          ? "mobile"
          : "desktop",

      resultsCount

    });

    // =====================================
    // 🔥 AUTO LEARN SYNONYMS
    // =====================================

    if (
      type === "search" &&
      normalizedQuery
    ) {

      const synonymGroups =
        await Synonym.find({

          store:
            normalizedStore,

          query: {
            $ne:
              normalizedQuery
          }

        })
          .select("query synonyms")
          .limit(50);

      for (const item of synonymGroups) {

        if (
          item.query ===
          normalizedQuery
        ) {
          continue;
        }

        const score =
          stringSimilarity
            .compareTwoStrings(

              normalizedQuery,

              item.query

            );

        // TYPO / CLOSE MATCH
        if (
          score >= 0.86 &&
          Math.abs(
            normalizedQuery.length -
            item.query.length
          ) <= 2
        ) {

          const existingSynonym =
            item.synonyms.find(

              s =>
                s.word ===
                normalizedQuery

            );

          // UPDATE EXISTING
          if (existingSynonym) {

            existingSynonym.usageCount += 1;

            existingSynonym.confidence =
              Math.max(

                existingSynonym.confidence || 0,

                score

              );

          }

          // SAVE ONLY AFTER
          // 10 SEARCHES

          if (!existingSynonym) {
            item.synonyms.push({
              word:
                normalizedQuery,
              usageCount: 1,
              autoGenerated: true,
              confidence: score
            });
            await item.save();
          }
          else if (
            existingSynonym.usageCount % 10 === 0
          ) {
            await item.save();
          }
        }
      }

    }

    res.json({
      success: true
    });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});

router.get("/analytics/stats", async (req, res) => {
  try {
    const now = new Date();

    const last7Days = new Date();
    last7Days.setDate(now.getDate() - 7);

    const prev7Days = new Date();
    prev7Days.setDate(now.getDate() - 14);

    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();

    const [
      currentSearches,
      prevSearches
    ] = await Promise.all([
      Analytics.countDocuments({
        type: "search",
        store:
          normalizedStore,
        createdAt: {
          $gte: last7Days
        }
      }),
      Analytics.countDocuments({
        type: "search",
        store:
          normalizedStore,
        createdAt: {
          $gte:
            prev7Days,
          $lt:
            last7Days
        }
      })
    ]);

    // 🔥 FUNCTION
    const calcGrowth = (current, prev) => {
      if (prev === 0) return 100;
      return (((current - prev) / prev) * 100).toFixed(1);
    };

    res.json({
      totalSearches: currentSearches,
      searchesGrowth: calcGrowth(currentSearches, prevSearches),

      // same logic clicks ke liye bhi lagao
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: err.message
    });
  }
});

router.get("/analytics/top-searches", async (req, res) => {

  try {

    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();

    const data =
      await Analytics.aggregate([

        {
          $match: {

            type: "search",

            store:
              normalizedStore,

            normalizedQuery: {
              $ne: ""
            }

          }
        },

        {
          $group: {
            _id: "$normalizedQuery",
            count: {
              $sum: 1
            }
          }
        },
        {
          $project: {

            _id: 0,

            query:
              "$_id",

            count: 1

          }
        },
        {
          $sort: {
            count: -1
          }
        },

        {
          $limit: 10
        }

      ]);

    res.json(data);

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }
}
);

router.get("/analytics/top-products", async (req, res) => {
  try {
    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const match = {
      type: "click",
      productId: {
        $exists: true,
        $ne: ""
      }
    };

    const normalizedStore =
      store?.trim()?.toLowerCase();
    if (normalizedStore) {
      match.store =
        normalizedStore;
    }

    const data = await Analytics.aggregate([
      { $match: match },
      {
        $group: {
          _id: "$productId",
          title: { $max: "$productTitle" },
          image: { $max: "$productImage" },
          count: { $sum: 1 }
        }
      },
      { $sort: { count: -1 } },
      { $limit: 5 }
    ]);

    res.json(data);

  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: err.message
    });
  }
});

router.get("/analytics/recent-searches", async (req, res) => {
  try {
    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();
    const data =
      await Analytics.find({

        normalizedQuery: {
          $ne: ""
        },

        type: "search",

        store:
          normalizedStore

      })
        .sort({
          createdAt: -1
        })
        .limit(5)
        .lean();

    res.json(data);

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }
}
);

router.get("/analytics/search-trends", async (req, res) => {
  try {
    const parsedDays =
      Number(req.query.days);

    const days =

      Number.isNaN(parsedDays) ||

        parsedDays <= 0 ||

        parsedDays > 365

        ? 7

        : parsedDays;

    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);
    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();
    const data = await Analytics.aggregate([
      {
        $match: {

          type: "search",

          normalizedQuery: {
            $ne: ""
          },

          createdAt: {
            $gte: startDate
          },

          store:
            normalizedStore

        },
      },
      {
        $group: {
          _id: {
            date: {
              $dateToString: {
                format: "%Y-%m-%d",
                date: "$createdAt",
              },
            },
          },
          count: { $sum: 1 },
        },
      },
      {
        $project: {

          _id: 0,

          date:
            "$_id.date",

          count: 1

        }
      },
      {
        $sort: { date: 1 },
      },
    ]);

    if (
      process.env.NODE_ENV !==
      "production"
    ) {

      console.log(
        "SEARCH TRENDS:",
        data
      );

    }

    res.json(data);

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

router.get("/analytics/stats/all", async (req, res) => {
  try {
    const totalSearches = await Analytics.countDocuments({
      type: "search",
      store: {
        $exists: true,
        $ne: ""
      }
    });

    const totalClicks = await Analytics.countDocuments({
      type: "click",
      store: {
        $exists: true,
        $ne: ""
      }
    });

    const stores = await Analytics.aggregate([
      {
        $match: {
          store: {
            $exists: true,
            $ne: ""
          }
        }
      },
      {
        $group: {
          _id: "$store",
          totalSearches: {
            $sum: { $cond: [{ $eq: ["$type", "search"] }, 1, 0] }
          },
          totalClicks: {
            $sum: { $cond: [{ $eq: ["$type", "click"] }, 1, 0] }
          }
        }
      }
    ]);

    const storesWithConversion = stores.map(s => ({
      ...s,
      conversionRate:
        s.totalSearches === 0
          ? 0
          : ((s.totalClicks / s.totalSearches) * 100).toFixed(1)
    }));

    res.json({
      totals: {
        totalSearches,
        totalClicks,
        conversionRate:
          totalSearches === 0
            ? 0
            : ((totalClicks / totalSearches) * 100).toFixed(1)
      },
      stores: storesWithConversion
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: err.message
    });

  }
});

router.delete(
  "/analytics/clear",
  async (req, res) => {

    try {

      const { store } = req.body;
      if (!store) {
        return res.status(400).json({
          error: "Store is required"
        });
      }
      const normalizedStore =
        store
          ?.trim()
          ?.toLowerCase();
      await Analytics.deleteMany({
        store:
          normalizedStore
      });

      res.json({
        message:
          "Store analytics deleted ✅"
      });

    } catch (err) {

      console.error(err);

      res.status(500).json({
        error: err.message
      });

    }
  }
);

router.get("/analytics/overview", async (req, res) => {

  try {

    const { store } = req.query;

    if (!store) {

      return res.status(400).json({
        error: "Store is required"
      });

    }

    const parsedDays =
      Number(req.query.days);

    const days =

      Number.isNaN(parsedDays) ||

        parsedDays <= 0 ||

        parsedDays > 365

        ? 7

        : parsedDays;

    const normalizedStore =
      store
        ?.trim()
        ?.toLowerCase();

    // =========================
    // 🔥 DATE RANGE
    // =========================

    const startDate =
      new Date();

    startDate.setDate(
      startDate.getDate() - days
    );

    // =========================
    // 🔥 PREVIOUS RANGE
    // =========================

    const prevStartDate =
      new Date();

    prevStartDate.setDate(
      prevStartDate.getDate() -
      days * 2
    );

    // =========================
    // 🔥 PARALLEL QUERIES
    // =========================

    const [

      totalSearches,

      prevSearches,

      totalClicks,

      zeroResults,

      avgResultsData

    ] = await Promise.all([

      // CURRENT SEARCHES
      Analytics.countDocuments({

        type: "search",

        store:
          normalizedStore,

        createdAt: {
          $gte: startDate
        }

      }),

      // PREVIOUS SEARCHES
      Analytics.countDocuments({

        type: "search",

        store:
          normalizedStore,

        createdAt: {

          $gte:
            prevStartDate,

          $lt:
            startDate

        }

      }),

      // TOTAL CLICKS
      Analytics.countDocuments({

        type: "click",

        store:
          normalizedStore,

        createdAt: {
          $gte: startDate
        }

      }),

      // ZERO RESULTS
      Analytics.countDocuments({

        type: "search",

        store:
          normalizedStore,

        resultsCount: 0,

        createdAt: {
          $gte: startDate
        }

      }),

      // AVG RESULTS
      Analytics.aggregate([

        {

          $match: {

            type: "search",

            store:
              normalizedStore,

            createdAt: {
              $gte: startDate
            }

          }

        },

        {

          $group: {

            _id: null,

            avgResults: {
              $avg:
                "$resultsCount"
            }

          }

        }

      ])

    ]);

    // =========================
    // 🔥 GROWTH FUNCTION
    // =========================

    const calcGrowth = (
      current,
      previous
    ) => {

      if (previous === 0) {

        return current > 0
          ? "+100%"
          : "0%";

      }

      const growth = (

        (
          (
            current - previous
          ) / previous
        ) * 100

      ).toFixed(1);

      return `${growth > 0 ? "+" : ""
        }${growth}%`;

    };

    // =========================
    // 🔥 CTR
    // =========================

    const ctr =
      totalSearches === 0
        ? 0
        : (

          (
            totalClicks /
            totalSearches
          ) * 100

        ).toFixed(1);

    // =========================
    // 🔥 ZERO RESULT RATE
    // =========================

    const zeroResultRate =
      totalSearches === 0
        ? 0
        : (

          (
            zeroResults /
            totalSearches
          ) * 100

        ).toFixed(1);

    // =========================
    // 🔥 RESPONSE
    // =========================

    res.json({

      days,

      totalSearches,

      totalClicks,

      ctr,

      zeroResultRate,

      avgResults:

        avgResultsData?.length

          ? avgResultsData[0]
            .avgResults
            .toFixed(1)

          : 0,

      searchGrowth:
        calcGrowth(

          totalSearches,

          prevSearches

        ),

      ctrGrowth: "0%",

      zeroResultGrowth:
        "0%"

    });

  } catch (err) {

    console.error(
      "OVERVIEW ERROR:",
      err
    );

    res.status(500).json({
      error: err.message
    });

  }

});

module.exports = router;