const express = require("express");
const router = express.Router();
const Analytics = require("../Models/analyticsModel");
const stringSimilarity = require("string-similarity");
const Synonym = require("../Models/synonymModel");

router.post("/analytics", async (req, res) => {

  try {

    const {
      vendor,
      type,
      query,
      productId,
      resultsCount: incomingResultsCount,
      productHandle,
      store,
      productTitle,
      productImage
    } = req.body;

    const allowedTypes = [
      "search",
      "click",
      "no_result"
    ];

    if (
      !allowedTypes.includes(type)
    ) {

      return res.status(400).json({
        error:
          "Invalid analytics type"
      });

    }

    if (
      process.env.NODE_ENV !==
      "production"
    ) {

      console.log(
        "BODY RECEIVED:",
        req.body
      );

    }

    if (!store) {

      return res.status(400).json({
        error:
          "Store is required"
      });

    }

    if (
      type === "search" &&
      !query?.trim()
    ) {

      return res.json({
        success: false
      });

    }

    const normalizedStore =
      store
        ?.trim()
        ?.toLowerCase();

    const normalizedQuery =
      query
        ?.trim()
        ?.toLowerCase();

    const userAgent =
      req.headers[
      "user-agent"
      ] || "";

    const resultsCount =
      type === "no_result"
        ? 0
        : Number(
          incomingResultsCount
        ) || 0;

    // =====================================
    // 🔥 SAVE ANALYTICS
    // =====================================

    await Analytics.create({

      type,

      query:
        query?.trim() || "",

      normalizedQuery,

      productId,

      productTitle:
        productTitle || null,

      productHandle:
        productHandle || null,

      productImage:
        productImage || null,

      vendor:
        vendor
          ?.trim()
          ?.toLowerCase() || null,

      store:
        normalizedStore,

      device:
        /ipad|tablet/i.test(
          userAgent
        )
          ? "tablet"
          : /mobile|android|iphone/i.test(
            userAgent
          )
            ? "mobile"
            : "desktop",
      resultsCount

    });

    // =====================================
    // 🔥 AUTO LEARN SYNONYMS
    // =====================================

    if (
      type === "search" &&
      normalizedQuery
    ) {

      const synonymGroups =
        await Synonym.find({

          store:
            normalizedStore,

          query: {
            $ne:
              normalizedQuery
          }

        })
          .select("query synonyms")
          .limit(50);

      for (const item of synonymGroups) {

        if (
          item.query ===
          normalizedQuery
        ) {
          continue;
        }

        const score =
          stringSimilarity
            .compareTwoStrings(

              normalizedQuery,

              item.query

            );

        // TYPO / CLOSE MATCH
        if (
          score >= 0.86 &&
          Math.abs(
            normalizedQuery.length -
            item.query.length
          ) <= 2
        ) {

          const existingSynonym =
            item.synonyms.find(

              s =>
                s.word ===
                normalizedQuery

            );

          // UPDATE EXISTING
          if (existingSynonym) {

            existingSynonym.usageCount += 1;

            existingSynonym.confidence =
              Math.max(

                existingSynonym.confidence || 0,

                score

              );

          }

          // SAVE ONLY AFTER
          // 10 SEARCHES

          if (!existingSynonym) {

            const alreadyTooMany =
              item.synonyms.length >= 20;
            if (alreadyTooMany) {
              continue;
            }
            item.synonyms.push({
              word:
                normalizedQuery,
              usageCount: 1,
              autoGenerated: true,
              confidence: score
            });

          }

          if (
            !existingSynonym ||
            existingSynonym.usageCount % 5 === 0
          ) {
            await item.save();

          }
        }
      }

    }

    res.json({
      success: true
    });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});

router.get("/analytics/stats", async (req, res) => {
  try {
    const now = new Date();

    const last7Days = new Date();
    last7Days.setDate(now.getDate() - 7);

    const prev7Days = new Date();
    prev7Days.setDate(now.getDate() - 14);

    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();

    const [

      currentSearches,
      prevSearches,
      currentClicks,
      prevClicks
    ] = await Promise.all([
      // CURRENT SEARCHES
      Analytics.countDocuments({
        type: "search",
        store:
          normalizedStore,
        createdAt: {
          $gte:
            last7Days
        }
      }),

      // PREVIOUS SEARCHES
      Analytics.countDocuments({
        type: "search",
        store:
          normalizedStore,
        createdAt: {
          $gte:
            prev7Days,
          $lt:
            last7Days
        }
      }),

      // CURRENT CLICKS
      Analytics.countDocuments({
        type: "click",
        store:
          normalizedStore,
        createdAt: {
          $gte:
            last7Days
        }
      }),

      // PREVIOUS CLICKS
      Analytics.countDocuments({
        type: "click",
        store:
          normalizedStore,
        createdAt: {
          $gte:
            prev7Days,
          $lt:
            last7Days
        }
      })
    ]);

    // 🔥 FUNCTION
    const calcGrowth = (current, prev) => {
      if (prev === 0) {
        return current > 0
          ? "+100%"
          : "0%";
      }
      const growth =
        (
          (
            (current - prev) /
            prev
          ) * 100
        ).toFixed(1);

      return `${growth > 0 ? "+" : ""
        }${growth}%`;
    };

    res.json({
      totalSearches:
        currentSearches,
      searchesGrowth:
        calcGrowth(
          currentSearches,
          prevSearches
        ),
      totalClicks:
        currentClicks,
      clicksGrowth:
        calcGrowth(
          currentClicks,
          prevClicks
        )
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: err.message
    });
  }
});

router.get("/analytics/top-searches", async (req, res) => {

  try {

    const {
      store,
      days: rawDays
    } = req.query;
    const parsedDays =
      Number(rawDays);
    const days =
      Number.isNaN(parsedDays) ||
        parsedDays <= 0 ||
        parsedDays > 365
        ? 7
        : parsedDays;
    const startDate =
      new Date();
    startDate.setDate(
      startDate.getDate() - days
    );

    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();

    const data =
      await Analytics.aggregate([

        {
          $match: {
            type: "search",

            store:
              normalizedStore,

            normalizedQuery: {
              $ne: ""
            },

            createdAt: {
              $gte: startDate
            }
          }
        },

        {
          $group: {

            _id:
              "$normalizedQuery",

            count: {
              $sum: 1
            },
            clicks: {
              $sum: {
                $cond: [
                  {
                    $gt: [
                      "$productId",
                      null
                    ]
                  },
                  1,
                  0
                ]
              }
            }
          }
        },
        {
          $project: {
            _id: 0,
            query: "$_id",
            count: 1,
            ctr: {
              $cond: [
                {
                  $eq: [
                    "$count",
                    0
                  ]
                },
                0,
                {
                  $round: [
                    {
                      $multiply: [
                        {
                          $divide: [
                            "$clicks",
                            "$count"
                          ]
                        },
                        100
                      ]
                    },
                    1
                  ]
                }
              ]
            },
            avgPosition: {
              $literal: 1
            }
          }
        },
        {
          $sort: {
            count: -1
          }
        },
        {
          $limit: 10
        }
      ]);

    res.json(data);

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }
}
);

router.get("/analytics/top-products", async (req, res) => {
  try {
    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const match = {
      type: "click",
      productId: {
        $exists: true,
        $nin: ["", null]
      }
    };

    const normalizedStore =
      store?.trim()?.toLowerCase();
    if (normalizedStore) {
      match.store =
        normalizedStore;
    }

    const data = await Analytics.aggregate([
      { $match: match },
      {
        $group: {
          _id: "$productId",
          title: { $max: "$productTitle" },
          image: { $max: "$productImage" },
          count: { $sum: 1 }
        }
      },
      { $sort: { count: -1 } },
      { $limit: 5 }
    ]);

    res.json(data);

  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: err.message
    });
  }
});

router.get("/analytics/recent-searches", async (req, res) => {
  try {
    const {
      store,
      days: rawDays
    } = req.query;

    const parsedDays =
      Number(rawDays);
    const days =
      Number.isNaN(parsedDays) ||
        parsedDays <= 0 ||
        parsedDays > 365
        ? 7
        : parsedDays;
    const startDate =
      new Date();
    startDate.setDate(
      startDate.getDate() - days
    );

    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();
    const data =
      await Analytics.find({

        normalizedQuery: {
          $ne: ""
        },

        type: "search",

        store:
          normalizedStore,

        createdAt: {
          $gte:
            startDate
        },

      })
        .sort({
          createdAt: -1
        })
        .limit(5)
        .lean();

    res.json(data);

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }
}
);

router.get("/analytics/search-trends", async (req, res) => {
  try {
    const parsedDays =
      Number(req.query.days);

    const days =

      Number.isNaN(parsedDays) ||

        parsedDays <= 0 ||

        parsedDays > 365

        ? 7

        : parsedDays;

    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);
    const { store } = req.query;
    if (!store) {
      return res.status(400).json({
        error: "Store is required"
      });
    }
    const normalizedStore =
      store?.trim()?.toLowerCase();
    const data = await Analytics.aggregate([
      {
        $match: {

          type: "search",

          normalizedQuery: {
            $ne: ""
          },

          createdAt: {
            $gte: startDate
          },

          store:
            normalizedStore

        },
      },
      {
        $group: {
          _id: {
            date: {
              $dateToString: {
                format: "%Y-%m-%d",
                date: "$createdAt",
              },
            },
          },
          count: { $sum: 1 },
        },
      },
      {
        $project: {

          _id: 0,

          date:
            "$_id.date",

          count:
            "$count"

        }
      },
      {
        $sort: { date: 1 },
      },
    ]);

    if (
      process.env.NODE_ENV !==
      "production"
    ) {

      console.log(
        "SEARCH TRENDS:",
        data
      );

    }

    res.json(data);

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
});

router.get("/analytics/stats/all", async (req, res) => {
  try {
    const totalSearches = await Analytics.countDocuments({
      type: "search",
      store: {
        $exists: true,
        $ne: ""
      }
    });

    const totalClicks = await Analytics.countDocuments({
      type: "click",
      store: {
        $exists: true,
        $ne: ""
      }
    });

    const stores = await Analytics.aggregate([
      {
        $match: {
          store: {
            $exists: true,
            $ne: ""
          }
        }
      },
      {
        $group: {
          _id: "$store",
          totalSearches: {
            $sum: { $cond: [{ $eq: ["$type", "search"] }, 1, 0] }
          },
          totalClicks: {
            $sum: { $cond: [{ $eq: ["$type", "click"] }, 1, 0] }
          }
        }
      }
    ]);

    const storesWithConversion = stores.map(s => ({
      ...s,
      conversionRate:

        s.totalSearches === 0

          ? 0

          : Number(

            (
              (
                s.totalClicks /
                s.totalSearches
              ) * 100
            ).toFixed(1)

          )
    }));

    res.json({
      totals: {
        totalSearches,
        totalClicks,
        conversionRate:

          totalSearches === 0
            ? 0
            : Number(
              (
                (
                  totalClicks /
                  totalSearches
                ) * 100
              ).toFixed(1)
            )
      },
      stores: storesWithConversion
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({
      error: err.message
    });

  }
});

router.delete(
  "/analytics/clear",
  async (req, res) => {

    try {

      const { store } = req.body;
      if (!store) {
        return res.status(400).json({
          error: "Store is required"
        });
      }
      const normalizedStore =
        store
          ?.trim()
          ?.toLowerCase();
      await Analytics.deleteMany({
        store:
          normalizedStore
      });

      res.json({
        message:
          "Store analytics deleted ✅"
      });

    } catch (err) {

      console.error(err);

      res.status(500).json({
        error: err.message
      });

    }
  }
);

router.get("/analytics/overview", async (req, res) => {

  try {

    const { store } = req.query;

    if (!store) {

      return res.status(400).json({
        error: "Store is required"
      });

    }

    const parsedDays =
      Number(req.query.days);

    const days =

      Number.isNaN(parsedDays) ||

        parsedDays <= 0 ||

        parsedDays > 365

        ? 7

        : parsedDays;

    const normalizedStore =
      store
        ?.trim()
        ?.toLowerCase();

    // =========================
    // 🔥 DATE RANGE
    // =========================

    const startDate =
      new Date();

    startDate.setDate(
      startDate.getDate() - days
    );

    // =========================
    // 🔥 PREVIOUS RANGE
    // =========================

    const prevStartDate =
      new Date();

    prevStartDate.setDate(
      prevStartDate.getDate() -
      days * 2
    );

    // =========================
    // 🔥 PARALLEL QUERIES
    // =========================

    const [

      totalSearches,
      prevSearches,
      totalClicks,
      prevClicks,
      zeroResults,
      prevZeroResults,
      avgResultsData,
      prevAvgResultsData

    ] = await Promise.all([

      // CURRENT SEARCHES
      Analytics.countDocuments({

        type: "search",

        store:
          normalizedStore,

        createdAt: {
          $gte: startDate
        }

      }),

      // PREVIOUS SEARCHES
      Analytics.countDocuments({

        type: "search",

        store:
          normalizedStore,

        createdAt: {

          $gte:
            prevStartDate,

          $lt:
            startDate

        }

      }),

      // TOTAL CLICKS
      Analytics.countDocuments({

        type: "click",

        store:
          normalizedStore,

        createdAt: {
          $gte: startDate
        }

      }),
      // PREVIOUS CLICKS
      Analytics.countDocuments({
        type: "click",
        store:
          normalizedStore,
        createdAt: {
          $gte:
            prevStartDate,
          $lt:
            startDate
        }
      }),

      // ZERO RESULTS
      Analytics.countDocuments({

        type: "search",

        store:
          normalizedStore,

        resultsCount: 0,

        createdAt: {
          $gte: startDate
        }

      }),

      // PREVIOUS ZERO RESULTS
      Analytics.countDocuments({
        type: "search",
        store:
          normalizedStore,
        resultsCount: 0,
        createdAt: {
          $gte:
            prevStartDate,
          $lt:
            startDate
        }
      }),

      // AVG RESULTS
      Analytics.aggregate([

        {
          $match: {
            type: "search",
            store:
              normalizedStore,
            createdAt: {
              $gte: startDate
            }
          }
        },

        {
          $group: {
            _id: null,
            avgResults: {
              $avg:
                "$resultsCount"
            }
          }
        }

      ]),

      // PREVIOUS AVG RESULTS
      Analytics.aggregate([

        {
          $match: {
            type: "search",
            store:
              normalizedStore,
            createdAt: {
              $gte:
                prevStartDate,
              $lt:
                startDate
            }
          }
        },

        {
          $group: {
            _id: null,
            avgResults: {
              $avg:
                "$resultsCount"
            }
          }
        }

      ]),

    ]);

    // =========================
    // 🔥 GROWTH FUNCTION
    // =========================

    const calcGrowth = (
      current,
      previous
    ) => {

      if (previous === 0) {

        return current > 0
          ? "+100%"
          : "0%";

      }

      const growth = Number(
        (
          (
            (
              current - previous
            ) / previous
          ) * 100
        ).toFixed(1)

      );

      return `${growth > 0 ? "+" : ""
        }${growth}%`;

    };

    // =========================
    // 🔥 CTR
    // =========================
    const ctr =
      totalSearches === 0
        ? 0
        : Number(
          (
            (
              totalClicks /
              totalSearches
            ) * 100
          ).toFixed(1)
        );

    // =========================
    // 🔥 Previous CTR
    // =========================
    const prevCtr =
      prevSearches === 0
        ? 0
        : Number(
          (
            (
              prevClicks /
              prevSearches
            ) * 100
          ).toFixed(1)
        );

    // =========================
    // 🔥 ZERO RESULT RATE
    // =========================
    const zeroResultRate =
      totalSearches === 0
        ? 0
        : Number(
          (
            (
              zeroResults /
              totalSearches
            ) * 100
          ).toFixed(1)

        );

    // =========================
    // 🔥 Previous ZERO RESULT RATE
    // =========================

    const prevZeroRate =
      prevSearches === 0
        ? 0
        : Number(
          (
            (
              prevZeroResults /
              prevSearches
            ) * 100
          ).toFixed(1)

        );

    // =========================
    // 🔥 RESPONSE
    // =========================
    res.json({
      days,
      totalSearches,
      totalClicks,
      ctr,
      zeroResultRate,
      avgResults:
        avgResultsData?.length
          ? Number(
            avgResultsData[0]
              .avgResults
              .toFixed(1)
          )
          : 0,
      avgResultsGrowth:
        calcGrowth(
          Number(
            avgResultsData?.[0]
              ?.avgResults || 0
          ),
          Number(
            prevAvgResultsData?.[0]
              ?.avgResults || 0
          )
        ),
      searchGrowth:
        calcGrowth(
          totalSearches,
          prevSearches
        ),
      ctrGrowth:
        calcGrowth(
          Number(ctr),
          Number(prevCtr)
        ),
      zeroResultGrowth:
        calcGrowth(
          Number(zeroResultRate),
          Number(prevZeroRate)
        )
    });
  } catch (err) {
    console.error(
      "OVERVIEW ERROR:",
      err
    );
    res.status(500).json({
      error: err.message
    });
  }
});

router.get("/analytics/device-split", async (req, res) => {

  try {
    const {
      store,
      days: rawDays
    } = req.query;
    const parsedDays =
      Number(rawDays);
    const days =
      Number.isNaN(parsedDays) ||
        parsedDays <= 0 ||
        parsedDays > 365
        ? 7
        : parsedDays;
    const startDate =
      new Date();
    startDate.setDate(
      startDate.getDate() - days
    );
    if (!store) {
      return res.status(400).json({
        error:
          "Store is required"
      });
    }
    const normalizedStore =
      store
        ?.trim()
        ?.toLowerCase();

    const data =
      await Analytics.aggregate([
        {
          $match: {
            type: "search",
            createdAt: {
              $gte: startDate
            },
            store:
              normalizedStore,
            device: {
              $in: [
                "mobile",
                "desktop",
                "tablet"
              ]
            }
          }
        },
        {
          $group: {
            _id:
              "$device",
            count: {
              $sum: 1
            }
          }
        }
      ]);
    const total =
      data.reduce(
        (sum, item) =>
          sum + item.count,
        0
      );
    const result = [
      "mobile",
      "desktop",
      "tablet"
    ].map((device) => {
      const found =
        data.find(
          d =>
            d._id ===
            device
        );
      const count =
        found?.count || 0;
      return {
        name:
          device.charAt(0)
            .toUpperCase() +
          device.slice(1),
        value:
          total === 0
            ? 0
            : Number(
              (
                (count / total) * 100
              ).toFixed(1)
            )
      };
    });
    res.json(result);
  } catch (err) {
    console.error(err);
    res.status(500).json({
      error:
        err.message
    });
  }
}
);

router.get("/analytics/recommendation", async (req, res) => {

  try {
    const { store } =
      req.query;
    const normalizedStore =
      store
        ?.trim()
        ?.toLowerCase();
    const topSearch =
      await Analytics.aggregate([
        {
          $match: {
            type: "search",
            store:
              normalizedStore
          }
        },
        {
          $group: {
            _id:
              "$normalizedQuery",
            searches: {
              $sum: 1
            }
          }
        },
        {
          $sort: {
            searches: -1
          }
        },
        {
          $limit: 1
        }
      ]);
    if (!topSearch.length) {
      return res.json({
        message:
          "No recommendations available yet."
      });
    }
    res.json({
      message:
        `"${topSearch[0]._id}" is currently trending. Consider featuring related products on your homepage.`
    });
  } catch (err) {
    res.status(500).json({
      error: err.message
    });
  }
}
);

module.exports = router;