const express = require("express");
const router = express.Router();
const Synonym = require("../Models/synonymModel");

// ADD SYNONYM
router.post("/add", async (req, res) => {

  const {
    query,
    synonym,
    store
  } = req.body;

  const normalizedStore =
    store?.trim()?.toLowerCase();

  const normalizedQuery =
    query?.trim()?.toLowerCase();

  const normalizedSynonym =
    synonym?.trim()?.toLowerCase();

  if (
    !query ||
    !synonym ||
    !store
  ) {

    return res.status(400).json({
      error:
        "Query, synonym and store are required"
    });

  }

  try {

    const existing =
      await Synonym.findOne({

        query:
          normalizedQuery,

        store:
          normalizedStore

      });

    if (existing) {

      if (

        !existing.synonyms.some(

          s =>
            s.word ===
            normalizedSynonym

        )

      ) {

        existing.synonyms.push({

          word:
            normalizedSynonym,

          usageCount: 1,

          autoGenerated: false,

          confidence: 1

        });

      }

      await existing.save();

      return res.json(existing);

    }

    const newSynonym =
      await Synonym.create({

        query:
          normalizedQuery,

        synonyms: [

          {

            word:
              normalizedSynonym,

            usageCount: 1,

            autoGenerated: false,

            confidence: 1

          }

        ],

        store:
          normalizedStore

      });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});


// =========================
// 📋 LIST SYNONYMS
// =========================
router.get("/list", async (req, res) => {

  try {

    const { store } = req.query;

    const normalizedStore =
      store?.trim()?.toLowerCase();

    if (!store) {

      return res.status(400).json({
        error: "Store is required"
      });

    }

    const synonyms =
      await Synonym
        .find({
          store:
            normalizedStore
        })
        .sort({
          createdAt: -1
        })
        .lean();

    res.json({
      synonyms
    });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});

// =========================
// 🗑 DELETE SYNONYM
// =========================
router.delete("/delete/:id", async (req, res) => {

  try {

    const { store } = req.body;

    const normalizedStore =
      store?.trim()?.toLowerCase();

    if (!store) {

      return res.status(400).json({
        error: "Store is required"
      });

    }

    await Synonym.findOneAndDelete({

      _id: req.params.id,

      store:
        normalizedStore

    });

    res.json({
      success: true
    });

  } catch (err) {

    console.error(err);

    res.status(500).json({
      error: err.message
    });

  }

});

module.exports = router;