const mongoose =
  require("mongoose");

const schema =
  new mongoose.Schema({

    // ======================
    // 🔥 MAIN QUERY
    // ======================

    query: {
      type: String,
      required: true,
      index: true
    },

    // ======================
    // 🔥 SYNONYMS
    // ======================

    synonyms: [

      {

        word: {
          type: String,
          required: true
        },

        usageCount: {
          type: Number,
          default: 1
        },

        autoGenerated: {
          type: Boolean,
          default: false
        },

        confidence: {
          type: Number,
          default: 0
        }

      }

    ],

    // ======================
    // 🔥 STORE
    // ======================

    store: {
      type: String,
      required: true,
      index: true
    }

  }, {
    timestamps: true
  });


// ======================
// 🔥 INDEXES
// ======================

schema.index({
  store: 1,
  query: 1
}, {
  unique: true
});

schema.index({
  "synonyms.word": 1
});

module.exports =
  mongoose.model(
    "Synonym",
    schema
  );